name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: NodeJS version to uses
    default: 20.x
    required: true
  working-dir: 
    description: The working directory of the application
    default: .
    required: false
  target-env:
    description: '"dev" or "prod". Controls whether dev dependencies are installed'
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{inputs.working-dir}}/node_modules
        key: node-modules-${{inputs.target-env}}-${{hashFiles(format('{0}/{1}',inputs.working-dir, 'package-lock.json'))}} #format function to evaluate values correctly
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev'}} # if target-env is dev run npm ci or else with omit 
      shell: bash                       # whenever within a composite action, provide shell step 
      working-directory: ${{inputs.working-dir}}   # provide working directory as well for composite
    