name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: NodeJS version to uses
    default: 20.x
    required: true
  working-dir: 
    description: The working directory of the application
    default: .
    required: false
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{inputs.working-dir}}/node_modules
        key: node-modules-${{hashFiles('${{inputs.working-dir}}/package-lock.json')}}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: nmp ci 
      shell: bash                       # whenever within a composite action, provide shell step 
      working-directory: ${{inputs.working-dir}}   # provide working directory as well for composite